# conf/train.yaml

train:          True
valid:          True

hyper:
    batch_size:     16
    num_workers:    24

    learning_rate:  1e-5
    num_epochs:     3

    lr_step:        2
    lr_gamma:       0.9
    beta1:          0.9
    beta2:          0.999
